version: '3'
services:
  nginx:
    image: nginx
    ports:
      - ${STAC_FASTAPI_NGINX_PORT:-80}:80
      - ${STAC_FASTAPI_NGINX_PORT:-443}:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/conf.d/:ro
      - ../stac-browser-dist/:/var/www/
    depends_on:
      - app-pgstac
      #- app-sqlalchemy
    command: [ "nginx-debug", "-g", "daemon off;" ]

  app-pgstac:
    environment:
      - UVICORN_ROOT_PATH=/api/v1/pgstac
  # app-sqlalchemy:
  #   environment:
  #     - UVICORN_ROOT_PATH=/api/v1/sqlalchemy