version: '3'
services:
  stac-fastapi-sqlalchemy:
    image: ghcr.io/stac-utils/stac-fastapi:latest-sqlalchemy
    platform: linux/amd64
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=pgstac
      - POSTGRES_HOST_WRITER=pgstac
      - POSTGRES_PORT=5432
      - WEB_CONCURRENCY=10
    ports:
      - "8080:8080"
    depends_on:
      - pgstac

  pgstac:
    image: ghcr.io/stac-utils/pgstac:v0.6.13
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=localhost
      - PGDATABASE=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500

  migrate:
    image: ghcr.io/stac-utils/stac-fastapi:latest-sqlalchemy
    command: bash -c "cd /app && alembic upgrade head"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST=pgstac
      - POSTGRES_PORT=5432
    depends_on:
      - stac-fastapi-sqlalchemy

networks:
  default:
    name: stac-fastapi-network
